import { Layout } from "@/ui/components/layout/layout";
import { Seo } from "@/ui/components/seo/seo";
import { UserAccountContainer } from "@/ui/modules/user-profiles/user-account/user-account.container";

export default function Connexion() {
  return (
    <>
      <Seo title="Mon espace" description="Generated by Alexia" />

      <Layout withSideBar>
        <UserAccountContainer/>
      </Layout>
    </>
  );
}
