import { Layout } from "@/ui/components/layout/layout";
import { Seo } from "@/ui/components/seo/seo";
import { LandingPageContainer } from "@/ui/modules/landing-page/components/landing-page.container";

export default function Home() {
  return (
    <>
      <Seo title="Millions Max" description="Generated by Alexia" />

      <Layout isDisplayBreadCrums={false}>
        <LandingPageContainer />
      </Layout>
    </>
  );
}
