
import { Layout } from "@/ui/components/layout/layout";
import { Seo } from "@/ui/components/seo/seo";
import { LoginContainer } from "@/ui/modules/authentification/login/login.conatiner";

export default function Connexion() {
  return (
    <>
      <Seo title="Connexion sur coders Monkeys" description="Generated by Alexia" />

      <Layout >
        <LoginContainer/>
      </Layout>
    </>
  );
}
