import { GUEST } from "@/lib/session-status";
import { Layout } from "@/ui/components/layout/layout";
import { Seo } from "@/ui/components/seo/seo";
import { ForgetPasswordContainer } from "@/ui/modules/authentification/forget-password/forget-password.container";

export default function ForgetPassword() {
  return (
    <>
      <Seo title="Millions Max" description="Generated by Alexia" />

      <Layout sessionStatus = {GUEST} >
        <ForgetPasswordContainer/>
      </Layout>
    </>
  );
}
