//COMPOSANT
import { Container } from "@/ui/components/container/container";
import { Seo } from "@/ui/components/seo/seo";

//DESIGN SYSTEM
import { Avatar } from "@/ui/avatar/avatar";
import { Button } from "@/ui/design-system/button/button";
import { Logo } from "@/ui/design-system/logo/logo";
import { Spinner } from "@/ui/design-system/spinner/spinner";
import { Typography } from "@/ui/design-system/typography/typography";

//ICO
import { RiUser6Fill } from "react-icons/ri";
import { Layout } from "@/ui/components/layout/layout";

export default function DesignSystem(){
    return(
        <>
            <Seo title="Design System" description="Generated by Alexia" />

            <Layout> 
                <Container className="py-10 space-y-10">
                    <div className="flex items-center gap-4 p-4">
                        <Typography variant="caption1" component="h3">
                            Texte en vert, taille 2xl
                        </Typography>
                        <Typography theme="primary" variant="caption2" component="h1">
                            Texte en vert, taille 2xl
                        </Typography>
                        <Typography theme="secondary" variant="caption4" component="h1">
                            Texte en vert, taille 2xl
                        </Typography>
                        <Typography theme="gray" variant="caption4" component="h1">
                            Texte en vert, taille 2xl
                        </Typography>
                    </div>

                    {/*Spinner*/}
                    <Typography variant="h5" component="h1">
                        Spinner
                    </Typography>
                    <div className="flex items-center gap-4 p-4">
                        <Spinner size="small" />
                        <Spinner />
                        <Spinner size="large" />
                    </div>

                    {/*Button */}
                    <Typography variant="h5" component="h1">
                        Button / icon/ isloading
                    </Typography>
                    <div className="flex items-center gap-4 p-5" >
                        <Button isLoading
                            size="small">
                            Accent</Button>
                        <Button isLoading
                            size="small"
                            variant="secondary">Secondary</Button>
                        <Button isLoading
                            size="small"
                            variant="outline">Alexia</Button>
                        <Button isLoading
                            size="small"
                            variant="disable">Alexia</Button>
                        <Button isLoading
                            size="small"
                            variant="ico" icon={{ icon: RiUser6Fill }} />
                    </div>
                    <div className="flex items-center gap-4 p-5">
                        <div className="flex items-center gap-4 p-5" >
                            <Button size="small"> Accent</Button>
                            <Button size="small" variant="secondary">Secondary</Button>
                            <Button size="small" variant="outline">Alexia</Button>
                            <Button size="small" variant="disable">Alexia</Button>
                            <Button size="small" variant="ico" icon={{ icon: RiUser6Fill }} />
                        </div>
                    </div>
                    <div>
                        <div className="flex items-center gap-4 p-5" >
                            <Button size="medium"> Accent</Button>
                            <Button size="medium" variant="secondary">Secondary</Button>
                            <Button size="medium" variant="outline">Alexia</Button>
                            <Button size="medium" variant="disable">Alexia</Button>
                            <Button size="medium" variant="ico" icon={{ icon: RiUser6Fill }} />
                        </div>
                    </div>
                    <div>
                        <div className="flex items-center gap-4 p-5">
                            <Button size="large"> Accent</Button>
                            <Button size="large" variant="secondary">Secondary</Button>
                            <Button size="large" variant="outline">Alexia</Button>
                            <Button size="large" variant="disable" icon={{ icon: RiUser6Fill }}>Alexia</Button>
                            <Button size="large" variant="ico" icon={{ icon: RiUser6Fill }} />
                        </div>
                    </div>

                    <div>
                        <Typography variant="caption3" component="h3">
                            logo
                        </Typography>
                        <div className="flex items-center gap-4 p-5">
                            <Logo size="very-small" />
                            <Logo size="small" />
                            <Logo />
                            <Logo size="large" />
                        </div>
                    </div>
                    <div>
                        <Typography variant="caption3" component="h3">
                            Avatar
                        </Typography>
                        <div className="flex items-center gap-4 p-5">
                            <Avatar size="small" src="/assets/images/logo.jpg" alt="Avatar de Mali Yoko" />
                            <Avatar src="/assets/images/logo.jpg" alt="Avatar de Mali Yoko" />
                            <Avatar size="large" src="/assets/images/logo.jpg" alt="Avatar de Mali Yoko" />
                        </div>
                    </div>

                </Container>
            </Layout>
            
        </>
    )
}