import { REGISTERED } from "@/lib/session-status";
import { Seo } from "@/ui/components/seo/seo";
import { Session } from "@/ui/components/session/session";
import { OnboardingContainer } from "@/ui/modules/onboarding/onboardingContainer";

export default function Onboarding() {
  return (
    <>
      <Seo title="Onboarding" description="Generated by Alexia" />

      <Session sessionStatus = {REGISTERED}>
        <OnboardingContainer/>
      </Session>
    </>
  );
}
